esphome:
  name: alarm
  platform: ESP8266
  board: nodemcuv2
  
  includes:
    - paradox_combus_src/

wifi:
  ssid: !secret wifi_name
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "alarm"
    password: !secret wifi_password

#captive_portal:

# Enable logging
logger:
  baud_rate: 0

# Enable Home Assistant API
api:

ota:

status_led:
  pin:
    number: D4
    inverted: yes

custom_component:
- lambda: |-
    auto combusEsp = new ParadoxCombusEsphome();
    
    combusEsp->onAlarmStatusChange([&](std::string statusCode) {
      if (id(alarm_status).state != statusCode) {
        id(alarm_status).publish_state(statusCode);
      }
    });
    
    combusEsp->onZoneStatusChange([&](uint8_t zone, bool open) {
      switch (zone) {
        case 1: id(z1).publish_state(open); break;
        case 2: id(z2).publish_state(open); break;
        case 3: id(z3).publish_state(open); break;
        case 4: id(z4).publish_state(open); break;
        case 5: id(z5).publish_state(open); break;
        case 6: id(z6).publish_state(open); break;
        case 7: id(z7).publish_state(open); break;
        case 8: id(z8).publish_state(open); break;
        case 9: id(z9).publish_state(open); break;
      }
    });
    return {combusEsp};

binary_sensor:
  - platform: template
    id: z1
    name: "Entrance motion"
    device_class: motion
  - platform: template
    id: z2
    name: "Living room motion"
    device_class: motion
  - platform: template
    id: z3
    name: "Terrace door"
    device_class: door
  - platform: template
    id: z4
    name: "Service room motion"
    device_class: motion
  - platform: template
    id: z5
    name: "Service room door"
    device_class: door
  - platform: template
    id: z6
    name: "Child room motion"
    device_class: motion
  - platform: template
    id: z7
    name: "Bedroom motion"
    device_class: motion
  - platform: template
    id: z8
    name: "Smoke detector"
    device_class: smoke
  - platform: template
    id: z9
    name: "Entrance door"
    device_class: door

text_sensor:
  - platform: template
    id: alarm_status
    name: "Alarm Status"
    icon: "mdi:shield"
    
switch:
  - platform: template
    name: "Alarm Connection"
    id: connection_status_switch
    lambda: |-
      return getCombusConnectionStatus();
    icon: "mdi:shield-link-variant"
    turn_on_action:
      - switch.toggle: restart_switch
    turn_off_action:
      - lambda: |-
          disconnectCombus();
  - platform: restart
    id: restart_switch

