esphome:
  name: alarm
  platform: ESP8266
  board: nodemcuv2

external_components:
  - source:
      type: local
      path: components

wifi:
  ssid: !secret wifi_name
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "alarm"
    password: !secret wifi_password

# Enable logging
logger:
  baud_rate: 0

# Enable Home Assistant API
api:

ota:

status_led:
  pin:
    number: D4
    inverted: yes

paradox_combus:
  id: combus
  clk_pin: D1
  dta_pin: D2

binary_sensor:
  - platform: paradox_combus
    paradox_combus_id: combus
    zone: 1
    name: "Entrance motion"
    device_class: motion
  - platform: paradox_combus
    paradox_combus_id: combus
    zone: 2
    name: "Living room motion"
    device_class: motion
  - platform: paradox_combus
    paradox_combus_id: combus
    zone: 3
    name: "Terrace door"
    device_class: door
  - platform: paradox_combus
    paradox_combus_id: combus
    zone: 4
    name: "Service room motion"
    device_class: motion
  - platform: paradox_combus
    paradox_combus_id: combus
    zone: 5
    name: "Service room door"
    device_class: door
  - platform: paradox_combus
    paradox_combus_id: combus
    zone: 6
    name: "Child room motion"
    device_class: motion
  - platform: paradox_combus
    paradox_combus_id: combus
    zone: 7
    name: "Bedroom motion"
    device_class: motion
  - platform: paradox_combus
    paradox_combus_id: combus
    zone: 8
    name: "Smoke detector"
    device_class: smoke
  - platform: paradox_combus
    paradox_combus_id: combus
    zone: 9
    name: "Entrance door"
    device_class: door

text_sensor:
  - platform: paradox_combus
    paradox_combus_id: combus
    type: alarm_status
    name: "Alarm Status"
    icon: "mdi:shield"


alarm_control_panel:
  - platform: paradox_combus
    paradox_combus_id: combus
    name: "Alarm"
    # IMPORTANT: these are example bytes and will likely need adjustment for your panel/code.
    disarm_sequence: [0x31, 0x32, 0x33, 0x34]
    arm_home_sequence: [0x53]
    arm_away_sequence: [0x41]
    arm_night_sequence: [0x4E]
